title: Ruibing Jin
position: Scientist
affiliation: A*star
email: ruibing_jin(at)outlook(dot)com
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=iqloFEEAAAAJ
github_link: https://github.com/ruibing-jin
linkedin: https://sg.linkedin.com/in/ruibing-jin-0124a2a3
avatar: ./assets/img/ruibing.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
