title: Ruibing Jin
position: Lead Data Scientist/Team Lead
affiliation: TikTok
email: ruibing_jin(at)outlook(dot)com
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=iqloFEEAAAAJ
github_link: https://github.com/ruibing-jin
linkedin: https://sg.linkedin.com/in/ruibing-jin-0124a2a3
avatar: ./assets/img/ruibing_jin.png
google_analytics: G-7ETJRETJ5W
favicon: ./assets/img/ai_icon.png
favicon_dark: ./assets/img/ai_icon.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
